<?php

namespace App\Http\Livewire\Reports;

use Livewire\Component;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use App\Models\BranchesModel;
use App\Models\LoansModel;
use App\Models\sub_products;
use DateTime;
use Illuminate\Support\Facades\DB;

class LoanApplicationReport extends LivewireDatatable
{
    public $exportable=true;

    function builder(){
        $query=LoansModel::query();

        return $query;
    }

    public function columns()
    {
        return [
            column::name('created_at')->label('Report date'),
            column::name('loan_id')->label('id'),
            column::name('loan_account_number')->label('account number'),
            column::name('client_number')->label('client number'),
            column::callback('loan_sub_product',function($sub_product_id){
                return DB::table('loan_sub_products')->where('sub_product_id',$sub_product_id)->value('sub_product_name');
            })->label('product name'),
            column::name('guarantor')->label('guarantor'),
            column::callback('branch_id',function($branch_id){
                return BranchesModel::where('id',$branch_id)->value('name');
            })->label('branch'),
            column::callback('principle',function($principle){
                return number_format($principle);
            })->label('principle')->searchable(),
            column::callback('interest',function ($interest){
                return $interest.'%';
            })->label('interest')->searchable(),
            column::name('heath')->label('health'),
            column::name('tenure')->label('tenure'),
            column::name('status')->label('status')


        ];

        // TODO: Change the autogenerated stub
    }


}
