<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('departments')->truncate();

        // Insert existing data
        $data = [
            [
                'id' => 1,
                'department_name' => 'Governance & Oversight',
                'department_code' => 'GOV',
                'parent_department_id' => null,
                'description' => 'Governance and oversight functions',
                'status' => true,
                'level' => 1,
                'path' => 0,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 2,
                'department_name' => 'Board of Directors',
                'department_code' => 'BOD',
                'parent_department_id' => 1,
                'description' => 'Elected governing body responsible for strategic direction and oversight. Approves policies and budgets, hires and evaluates the General Manager/CEO, oversees risk and compliance, ensures member interests are protected.',
                'status' => true,
                'level' => 2,
                'path' => 0.1,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 3,
                'department_name' => 'Supervisory Committee',
                'department_code' => 'SUP',
                'parent_department_id' => 1,
                'description' => 'Independent body that monitors internal controls, financial integrity, and board conduct. Conducts internal audits, policy compliance checks, and reports irregularities to members.',
                'status' => true,
                'level' => 2,
                'path' => 0.1,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 4,
                'department_name' => 'Core Management & Operations',
                'department_code' => 'CMO',
                'parent_department_id' => null,
                'description' => 'Core management and operational departments',
                'status' => true,
                'level' => 1,
                'path' => 0,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 5,
                'department_name' => 'Administration & General Services',
                'department_code' => 'AGS',
                'parent_department_id' => 4,
                'description' => 'Handles day-to-day office operations, facilities, and logistics. Office management, document control, transport, security, maintenance, procurement and logistics support.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 6,
                'department_name' => 'Finance & Accounting',
                'department_code' => 'FAC',
                'parent_department_id' => 4,
                'description' => 'Manages all financial activities and reporting. Budgeting and forecasting, financial statements and audits, payroll and expense management, tax and statutory compliance.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 7,
                'department_name' => 'Credit Department',
                'department_code' => 'CRD',
                'parent_department_id' => 4,
                'description' => 'Manages the full loan lifecycle. Loan application processing, risk and creditworthiness assessment, loan monitoring and recovery, delinquency management.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 8,
                'department_name' => 'Savings & Deposits',
                'department_code' => 'SVD',
                'parent_department_id' => 4,
                'description' => 'Handles member contributions and savings products. Savings account management, fixed deposits and share capital, withdrawal and interest processing.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 9,
                'department_name' => 'Member Services',
                'department_code' => 'MBS',
                'parent_department_id' => 4,
                'description' => 'Ensures quality service and member satisfaction. Member registration and onboarding, queries and support, member education and outreach.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 10,
                'department_name' => 'Internal Audit & Compliance',
                'department_code' => 'IAC',
                'parent_department_id' => 4,
                'description' => 'Provides assurance on internal controls and regulatory adherence. Regular audits and compliance reviews, fraud detection and investigations, risk monitoring.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 11,
                'department_name' => 'Human Resources',
                'department_code' => 'HRD',
                'parent_department_id' => 4,
                'description' => 'Manages personnel and workplace development. Recruitment and onboarding, staff performance and training, leave and benefits administration, policy development.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 12,
                'department_name' => 'Information Systems',
                'department_code' => 'ICT',
                'parent_department_id' => 4,
                'description' => 'Maintains technology infrastructure and digital services. Core banking system support, network security and data backups, mobile and online platform support, IT policy compliance.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 13,
                'department_name' => 'Marketing & Business Development',
                'department_code' => 'MBD',
                'parent_department_id' => 4,
                'description' => 'Drives member growth and product innovation. Branding and promotions, member recruitment, partnership building, product development.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 14,
                'department_name' => 'Legal & Governance',
                'department_code' => 'LGD',
                'parent_department_id' => 4,
                'description' => 'Manages legal matters and supports good governance practices. Contract review and drafting, legal dispute resolution, governance compliance, advising board and management.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 15,
                'department_name' => 'Risk Management',
                'department_code' => 'RMD',
                'parent_department_id' => 4,
                'description' => 'Assesses and mitigates organizational risks. Risk identification and registers, business continuity planning, insurance and crisis management.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
            [
                'id' => 16,
                'department_name' => 'Procurement & Logistics',
                'department_code' => 'PRL',
                'parent_department_id' => 4,
                'description' => 'Handles supply chain and acquisition of goods/services. Vendor selection and tendering, inventory and asset tracking, purchasing and delivery logistics.',
                'status' => true,
                'level' => 2,
                'path' => 0.4,
                'created_at' => '2025-07-17 16:25:47',
                'updated_at' => '2025-07-17 16:25:47',
                'deleted_at' => null,
                'branch_id' => null,
                'dashboard_type' => null,
            ],
        ];

        foreach ($data as $row) {
            DB::table('departments')->insert($row);
    }
}
}