<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ClientsModel;
use Carbon\Carbon;

class ExampleMembersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing records to avoid duplicates
        ClientsModel::truncate();

        // First Member
        ClientsModel::create([
            'account_number' => 'AC123',
            'first_name' => 'John',
            'middle_name' => 'Michael',
            'last_name' => 'Doe',
            'branch' => 'Main Branch',
            'registering_officer' => 'Officer A',
            'loan_officer' => 'Loan A',
            'approving_officer' => 'Approver A',
            'membership_type' => 'Individual',
            'incorporation_number' => 'INC123456',
            'phone_number' => '0755000001',
            'mobile_phone_number' => '0755000001',
            'email' => 'john.doe@example.com',
            'place_of_birth' => 'Dar es Salaam',
            'marital_status' => 'Single',
            'client_number' => '00001',
            'registration_date' => '2024-01-01',
            'address' => '123 Main St',
            'notes' => 'Note 1',
            'current_team_id' => 1,
            'profile_photo_path' => '/photos/john.jpg',
            'branch_id' => 101,
            'client_status' => 'ACTIVE',
            'next_of_kin_name' => 'Jane Doe',
            'next_of_kin_phone' => '0755111111',
            'tin_number' => 'TIN12345',
            'nida_number' => 'NIDA123456',
            'ref_number' => 'REF001',
            'shares_ref_number' => 'SHR001',
            'nationarity' => 'Tanzanian',
            'full_name' => 'John Michael Doe',
            'amount' => 1000.00,
            'national_id' => 'ID123456',
            'client_id' => 'CID001',
            'customer_code' => 'CUST001',
            'present_surname' => 'Doe',
            'birth_surname' => 'Doe',
            'number_of_spouse' => 0,
            'number_of_children' => 0,
            'classification_of_individual' => 'Individual',
            'gender' => 'Male',
            'date_of_birth' => '1990-01-01',
            'country_of_birth' => 'Tanzania',
            'fate_status' => 'Alive',
            'social_status' => 'Normal',
            'residency' => 'Resident',
            'citizenship' => 'Tanzanian',
            'nationality' => 'Tanzanian',
            'employment' => 'Employed',
            'employer_name' => 'Company A',
            'education' => 'University',
            'business_name' => 'Business A',
            'income_available' => 5000,
            'monthly_expenses' => 1000,
            'negative_status_of_individual' => 'None',
            'tax_identification_number' => 'TIN12345',
            'passport_number' => 'P1234567',
            'passport_issuer_country' => 'Tanzania',
            'driving_license_number' => 'D1234567',
            'voters_id' => 'V1234567',
            'custom_id_number_1' => 'CIDX001',
            'custom_id_number_2' => 'CIDX002',
            'main_address' => '123 Main St',
            'street' => 'Main St',
            'number_of_building' => '12',
            'postal_code' => '10000',
            'region' => 'Dar es Salaam',
            'district' => 'Ilala',
            'country' => 'Tanzania',
            'mobile_phone' => '0755000001',
            'fixed_line' => '0221000001',
            'trade_name' => 'Trade A',
            'legal_form' => 'Sole Proprietor',
            'establishment_date' => '2010-01-01',
            'registration_country' => 'Tanzania',
            'industry_sector' => 'Finance',
            'registration_number' => 'REG001',
            'middle_names' => 'Michael',
            'member_number' => '00001',
            'contact_number' => '0755000001',
            'occupation' => 'Engineer',
            'education_level' => 'Bachelor',
            'dependent_count' => 0,
            'annual_income' => 10000,
            'city' => 'Dar es Salaam',
            'status' => 'active',
            'religion' => 'Christian',
            'building_number' => '12',
            'ward' => 'Kivukoni',
            'accept_terms' => true,
            'application_type' => 'Online',
            'guarantor_region' => 'Dar es Salaam',
            'guarantor_ward' => 'Kivukoni',
            'guarantor_district' => 'Ilala',
            'guarantor_relationship' => 'Brother',
            'guarantor_membership_number' => 'GMEM001',
            'guarantor_full_name' => 'James Doe',
            'guarantor_email' => 'guarantor@example.com',
            'barua' => 'Y',
            'uthibitisho' => 'Y',
            'hisa' => 100,
            'akiba' => 50,
            'amana' => 200,
            'guarantor_first_name' => 'Peter',
            'guarantor_middle_name' => 'Andrew',
            'guarantor_last_name' => 'Doe',
            'income_source' => 'Employment',
            'share_payment_status' => 'Paid',
            'basic_salary' => 1500,
            'gross_salary' => 2500,
            'tax_paid' => 250,
            'pension' => 300,
            'nhif' => 150,
            'workers_union_etc' => 'None',
            'member_category' => 'Gold',
            'guarantor_phone' => '0755222222',
            'id_type' => 'NIDA',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);

        // Second Member
        ClientsModel::create([
            'account_number' => 'AC124',
            'first_name' => 'Mary',
            'middle_name' => 'Anne',
            'last_name' => 'Smith',
            'branch' => 'East Branch',
            'registering_officer' => 'Officer B',
            'loan_officer' => 'Loan B',
            'approving_officer' => 'Approver B',
            'membership_type' => 'Individual',
            'incorporation_number' => 'INC654321',
            'phone_number' => '0755000002',
            'mobile_phone_number' => '0755000002',
            'email' => 'mary.smith@example.com',
            'place_of_birth' => 'Arusha',
            'marital_status' => 'Married',
            'client_number' => '00002',
            'registration_date' => '2024-02-01',
            'address' => '456 Side St',
            'notes' => 'Note 2',
            'current_team_id' => 2,
            'profile_photo_path' => '/photos/mary.jpg',
            'branch_id' => 102,
            'client_status' => 'ACTIVE',
            'next_of_kin_name' => 'John Smith',
            'next_of_kin_phone' => '0755111122',
            'tin_number' => 'TIN54321',
            'nida_number' => 'NIDA654321',
            'ref_number' => 'REF002',
            'shares_ref_number' => 'SHR002',
            'nationarity' => 'Tanzanian',
            'full_name' => 'Mary Anne Smith',
            'amount' => 2000.00,
            'national_id' => 'ID654321',
            'client_id' => 'CID002',
            'customer_code' => 'CUST002',
            'present_surname' => 'Smith',
            'birth_surname' => 'Smith',
            'number_of_spouse' => 1,
            'number_of_children' => 2,
            'classification_of_individual' => 'Individual',
            'gender' => 'Female',
            'date_of_birth' => '1985-06-15',
            'country_of_birth' => 'Tanzania',
            'fate_status' => 'Alive',
            'social_status' => 'Normal',
            'residency' => 'Resident',
            'citizenship' => 'Tanzanian',
            'nationality' => 'Tanzanian',
            'employment' => 'Self-Employed',
            'employer_name' => 'Own Business',
            'education' => 'Diploma',
            'business_name' => 'Business B',
            'income_available' => 7000,
            'monthly_expenses' => 2000,
            'negative_status_of_individual' => 'None',
            'tax_identification_number' => 'TIN54321',
            'passport_number' => 'P7654321',
            'passport_issuer_country' => 'Tanzania',
            'driving_license_number' => 'D7654321',
            'voters_id' => 'V7654321',
            'custom_id_number_1' => 'CIDX003',
            'custom_id_number_2' => 'CIDX004',
            'main_address' => '456 Side St',
            'street' => 'Side St',
            'number_of_building' => '34',
            'postal_code' => '20000',
            'region' => 'Arusha',
            'district' => 'Arusha',
            'country' => 'Tanzania',
            'mobile_phone' => '0755000002',
            'fixed_line' => '0221000002',
            'trade_name' => 'Trade B',
            'legal_form' => 'Limited',
            'establishment_date' => '2012-05-01',
            'registration_country' => 'Tanzania',
            'industry_sector' => 'Retail',
            'registration_number' => 'REG002',
            'middle_names' => 'Anne',
            'member_number' => '00002',
            'contact_number' => '0755000002',
            'occupation' => 'Trader',
            'education_level' => 'Diploma',
            'dependent_count' => 2,
            'annual_income' => 15000,
            'city' => 'Arusha',
            'status' => 'active',
            'religion' => 'Muslim',
            'building_number' => '34',
            'ward' => 'Sakina',
            'accept_terms' => true,
            'application_type' => 'Offline',
            'guarantor_region' => 'Arusha',
            'guarantor_ward' => 'Sakina',
            'guarantor_district' => 'Arusha',
            'guarantor_relationship' => 'Sister',
            'guarantor_membership_number' => 'GMEM002',
            'guarantor_full_name' => 'Grace Smith',
            'guarantor_email' => 'grace@example.com',
            'barua' => 'Y',
            'uthibitisho' => 'Y',
            'hisa' => 200,
            'akiba' => 100,
            'amana' => 400,
            'guarantor_first_name' => 'Alice',
            'guarantor_middle_name' => 'Grace',
            'guarantor_last_name' => 'Smith',
            'income_source' => 'Self-employment',
            'share_payment_status' => 'Paid',
            'basic_salary' => 2000,
            'gross_salary' => 3000,
            'tax_paid' => 300,
            'pension' => 400,
            'nhif' => 200,
            'workers_union_etc' => 'None',
            'member_category' => 'Silver',
            'guarantor_phone' => '0755333333',
            'id_type' => 'Passport',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now()
        ]);
    }
}