<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoanSubProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Insert NBC SACCOS loan products
        $data = [
            // 1. NBCSaccos butua
            [
                'sub_product_id' => 'LSP001',
                'product_id' => 'P001',
                'sub_product_name' => 'NBCSaccos butua',
                'prefix' => 'NBB',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 50000,
                'principle_max_value' => 150000,
                'min_term' => 1,
                'max_term' => 1,
                'interest_value' => 24.00, // 2% per month = 24% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0,
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'No',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'NBCSaccos butua - 1 month loan with 2% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 500,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 2. ONJA
            [
                'sub_product_id' => 'LSP002',
                'product_id' => 'P002',
                'sub_product_name' => 'ONJA',
                'prefix' => 'ONJ',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 50000,
                'principle_max_value' => 1000000,
                'min_term' => 3,
                'max_term' => 3,
                'interest_value' => 60.00, // 5% per month = 60% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0,
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'No',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'ONJA - 3 months loan with 5% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 500,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 3. MKOKO WA DHARURA
            [
                'sub_product_id' => 'LSP003',
                'product_id' => 'P003',
                'sub_product_name' => 'MKOKO WA DHARURA',
                'prefix' => 'MWD',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 100000,
                'principle_max_value' => 4000000,
                'min_term' => 12,
                'max_term' => 12,
                'interest_value' => 24.00, // 2% per month = 24% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA DHARURA - Emergency loan with 2% monthly interest and 0.3% management fee',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 500,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 4. MKOKO WA MAENDELEO MDOGO
            [
                'sub_product_id' => 'LSP004',
                'product_id' => 'P004',
                'sub_product_name' => 'MKOKO WA MAENDELEO MDOGO',
                'prefix' => 'MMD',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 100000,
                'principle_max_value' => 6000000,
                'min_term' => 18,
                'max_term' => 18,
                'interest_value' => 18.00, // 1.5% per month = 18% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA MAENDELEO MDOGO - Small development loan with 1.5% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 500,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5. MKOKO WA MAENDELEO MKUBWA
            [
                'sub_product_id' => 'LSP005',
                'product_id' => 'P005',
                'sub_product_name' => 'MKOKO WA MAENDELEO MKUBWA',
                'prefix' => 'MMK',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 1000000,
                'principle_max_value' => 40000000,
                'min_term' => 36,
                'max_term' => 36,
                'interest_value' => 12.00, // 1% per month = 12% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA MAENDELEO MKUBWA - Large development loan with 1% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 4,
                'ltv' => 67,
                'score_limit' => 550,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 10.0, // 10% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 6. MKOKO WA BIDHAA ZA NYUMBANI
            [
                'sub_product_id' => 'LSP006',
                'product_id' => 'P006',
                'sub_product_name' => 'MKOKO WA BIDHAA ZA NYUMBANI',
                'prefix' => 'MBN',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 200000,
                'principle_max_value' => 4000000,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => 24.00, // 2% per month = 24% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA BIDHAA ZA NYUMBANI - Home goods loan with 2% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 550,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 10.0, // 10% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 7. MKOKO WA WASTAAFU
            [
                'sub_product_id' => 'LSP007',
                'product_id' => 'P007',
                'sub_product_name' => 'MKOKO WA WASTAAFU',
                'prefix' => 'MWS',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 100000,
                'principle_max_value' => 4000000,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => 12.00, // 12% annually as per specification
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA WASTAAFU - Retiree loan with 12% annual interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Retiree Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 450,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 8. MKOKO WA WASTAAFU (DHARURA)
            [
                'sub_product_id' => 'LSP008',
                'product_id' => 'P008',
                'sub_product_name' => 'MKOKO WA WASTAAFU (DHARURA)',
                'prefix' => 'MWSD',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 100000,
                'principle_max_value' => 4000000,
                'min_term' => 12,
                'max_term' => 12,
                'interest_value' => 21.6, // 1.8% per month = 21.6% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA WASTAAFU (DHARURA) - Emergency retiree loan with 1.8% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Retiree Charges',
                'loan_multiplier' => 3,
                'ltv' => 67,
                'score_limit' => 450,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9. MKOKO WA CHAPCHAP
            [
                'sub_product_id' => 'LSP009',
                'product_id' => 'P009',
                'sub_product_name' => 'MKOKO WA CHAPCHAP',
                'prefix' => 'CHP',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 50000,
                'principle_max_value' => 2000000,
                'min_term' => 3,
                'max_term' => 3,
                'interest_value' => 48.00, // 4% per month = 48% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0,
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'No',
                'maintenance_fees' => 'No',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA CHAPCHAP - Quick disbursement loan with 4% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 2,
                'ltv' => 67,
                'score_limit' => 450,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 10. MKOKO WA BIASHARA
            [
                'sub_product_id' => 'LSP010',
                'product_id' => 'P010',
                'sub_product_name' => 'MKOKO WA BIASHARA',
                'prefix' => 'MKB',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 500000,
                'principle_max_value' => 20000000,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => 24.00, // 2% per month = 24% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3, // 0.3% of loan amount
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'Yes',
                'maintenance_fees' => 'Yes',
                'inactivity' => 60,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA BIASHARA - Business loan with 2% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Business Charges',
                'loan_multiplier' => 4,
                'ltv' => 67,
                'score_limit' => 600,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 15.0, // 15% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 11. MKOKO WA SIKUKUUU
            [
                'sub_product_id' => 'LSP011',
                'product_id' => 'P011',
                'sub_product_name' => 'MKOKO WA SIKUKUUU',
                'prefix' => 'MWS',
                'sub_product_status' => 'Active',
                'currency' => 'TZS',
                'disbursement_account' => 1,
                'collection_account_loan_interest' => 1,
                'collection_account_loan_principle' => 1,
                'collection_account_loan_charges' => 1,
                'collection_account_loan_penalties' => 1,
                'principle_min_value' => 50000,
                'principle_max_value' => 1000000,
                'min_term' => 1,
                'max_term' => 1,
                'interest_value' => 60.00, // 5% per month = 60% annually
                'interest_tenure' => 'annually',
                'principle_grace_period' => 0,
                'interest_grace_period' => 0,
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0,
                'ledger_fees' => 'No',
                'ledger_fees_value' => 0,
                'lock_guarantee_funds' => 'No',
                'maintenance_fees' => 'No',
                'inactivity' => 0,
                'requires_approval' => 'Yes',
                'allow_statement_generation' => 'Yes',
                'send_notifications' => 'Yes',
                'require_image_member' => 'Yes',
                'require_image_id' => 'Yes',
                'require_mobile_number' => 'Yes',
                'notes' => 'MKOKO WA SIKUKUUU - Holiday loan with 5% monthly interest',
                'loan_product_account' => '0101100012001220',
                'charges' => 'Standard Charges',
                'loan_multiplier' => 2,
                'ltv' => 67,
                'score_limit' => 400,
                'repayment_frequency' => 'monthly',
                'interest_account' => '010140004000',
                'fees_account' => '010140004100',
                'payable_account' => '0101100012001220',
                'insurance_account' => '0101400042004220',
                'loan_interest_account' => '010140004000',
                'loan_charges_account' => '010140004100',
                'loan_insurance_account' => '0101400042004220',
                'charge_product_account' => '010140004100',
                'insurance_product_account' => '0101400042004220',
                'penalty_value' => 5.0, // 5% penalty
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Process each record individually
        foreach ($data as $row) {
            // Check if record exists by sub_product_id
            $exists = DB::table('loan_sub_products')
                ->where('sub_product_id', $row['sub_product_id'])
                ->exists();

            if ($exists) {
                // Update existing record
                DB::table('loan_sub_products')
                    ->where('sub_product_id', $row['sub_product_id'])
                    ->update($row);
                    
                echo "Updated: " . $row['sub_product_name'] . "\n";
            } else {
                // Insert new record
                DB::table('loan_sub_products')->insert($row);
                echo "Inserted: " . $row['sub_product_name'] . "\n";
            }
        }
        
        echo "\nLoan sub-products seeding completed successfully!\n";
    }
}