<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProcessCodeConfigsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('process_code_configs')->truncate();

        // Insert existing data
        $data = [
            [
                'id' => 1,
                'process_code' => 'ASSET_DISP',
                'process_name' => 'Asset Disposal',
                'description' => 'Approval for asset disposal',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 2,
                'process_code' => 'BRANCH_CREATE',
                'process_name' => 'Create New Branch',
                'description' => 'Approval for creating a new branch',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 3,
                'process_code' => 'BRANCH_EDIT',
                'process_name' => 'Edit Branch Details',
                'description' => 'Approval for modifying branch information',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 4,
                'process_code' => 'BRANCH_DEACTIVATE',
                'process_name' => 'Deactivate Branch',
                'description' => 'Approval for deactivating a branch',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 5,
                'process_code' => 'CLIENT_REG',
                'process_name' => 'Client Registration',
                'description' => 'Approval for new client registration',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 6,
                'process_code' => 'CLIENT_EDIT',
                'process_name' => 'Edit Client Details',
                'description' => 'Approval for modifying client information',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 7,
                'process_code' => 'CLIENT_BLACKLIST',
                'process_name' => 'Blacklist Client',
                'description' => 'Approval for blacklisting a client',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 8,
                'process_code' => 'SHARE_PURCHASE',
                'process_name' => 'Share Purchase',
                'description' => 'Approval for share purchase transactions',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 9,
                'process_code' => 'SHARE_TRANSFER',
                'process_name' => 'Share Transfer',
                'description' => 'Approval for share transfers between members',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 10,
                'process_code' => 'SHARE_WITHDRAW',
                'process_name' => 'Share Withdrawal',
                'description' => 'Approval for share capital withdrawals',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 11,
                'process_code' => 'BLOCK_SHARE_ACC',
                'process_name' => 'Block Share Account',
                'description' => 'Approval for blocking share accounts',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 12,
                'process_code' => 'ACTIVATE_SHARE_ACC',
                'process_name' => 'Activate Share Account',
                'description' => 'Approval for activating share accounts',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 13,
                'process_code' => 'SAV_OPEN',
                'process_name' => 'Open Savings Account',
                'description' => 'Approval for opening new savings accounts',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 14,
                'process_code' => 'SAV_LARGE_WD',
                'process_name' => 'Large Savings Withdrawal',
                'description' => 'Approval for large savings withdrawals',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 5000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 15,
                'process_code' => 'SAV_CLOSE',
                'process_name' => 'Close Savings Account',
                'description' => 'Approval for closing savings accounts',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 16,
                'process_code' => 'FIXED_DEP_OPEN',
                'process_name' => 'Open Fixed Deposit',
                'description' => 'Approval for opening fixed deposits',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 10000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 17,
                'process_code' => 'FIXED_DEP_EARLY_WD',
                'process_name' => 'Early Fixed Deposit Withdrawal',
                'description' => 'Approval for early fixed deposit withdrawals',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 10000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 18,
                'process_code' => 'LOAN_APP',
                'process_name' => 'Loan Application',
                'description' => 'Approval for new loan applications',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 20,
                'process_code' => 'LOAN_REST',
                'process_name' => 'Loan Restructuring',
                'description' => 'Approval for loan restructuring',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 500000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 21,
                'process_code' => 'LOAN_WOFF',
                'process_name' => 'Loan Write-off',
                'description' => 'Approval for loan write-offs',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 100000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 22,
                'process_code' => 'PRODUCT_CRE',
                'process_name' => 'Create Product',
                'description' => 'Approval for creating new products',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 23,
                'process_code' => 'PROD_EDIT',
                'process_name' => 'Edit Product',
                'description' => 'Approval for modifying product details',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 24,
                'process_code' => 'PROD_DEACTIVATE',
                'process_name' => 'Deactivate Product',
                'description' => 'Approval for deactivating products',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 25,
                'process_code' => 'ACC_JOURNAL',
                'process_name' => 'Journal Entry',
                'description' => 'Approval for journal entries',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 26,
                'process_code' => 'ACC_ADJUST',
                'process_name' => 'Create an account',
                'description' => 'Create an account',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 27,
                'process_code' => 'SHARE_TRF',
                'process_name' => 'Share Transfer',
                'description' => 'Approval for share transfers',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 100.00,
                'max_amount' => 10000.00,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 28,
                'process_code' => 'SHARE_WD',
                'process_name' => 'Share Withdrawal',
                'description' => 'Share Withdrawal',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 100.00,
                'max_amount' => 50000000.00,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 29,
                'process_code' => 'SHARE_ISS',
                'process_name' => 'Share Issuance',
                'description' => 'Share Issuance',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 30,
                'process_code' => 'ACC_EDIT',
                'process_name' => 'Account Edit',
                'description' => 'Approval for account edits',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 31,
                'process_code' => 'ACC_CREATE',
                'process_name' => 'Account Adjustment',
                'description' => 'Approval for account adjustments',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 32,
                'process_code' => 'EXP_PETTY',
                'process_name' => 'Petty Cash',
                'description' => 'Approval for petty cash expenses',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => 1000000.00,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 33,
                'process_code' => 'EXP_OPERATING',
                'process_name' => 'Operating Expense',
                'description' => 'Approval for operating expenses',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 34,
                'process_code' => 'EXP_CAPITAL',
                'process_name' => 'Capital Expense',
                'description' => 'Approval for capital expenses',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 5000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 47,
                'process_code' => 'EXPENSE_REG',
                'process_name' => 'Expense Registration',
                'description' => 'Process for registering and approving expenses with budget validation',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => '["1","2","3"]',
                'second_checker_roles' => '["1","2"]',
                'min_amount' => 0,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-09-05 12:00:00',
                'updated_at' => '2025-09-05 12:00:00',
                'requires_approver' => true,
                'approver_roles' => '["1"]',
            ],
            [
                'id' => 48,
                'process_code' => 'EXPENSE_PAYMENT',
                'process_name' => 'Expense Payment',
                'description' => 'Process for paying approved expenses',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => '["1","2","4"]',
                'second_checker_roles' => '[]',
                'min_amount' => 0,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-09-05 12:00:00',
                'updated_at' => '2025-09-05 12:00:00',
                'requires_approver' => true,
                'approver_roles' => '["1","2"]',
            ],
            [
                'id' => 49,
                'process_code' => 'EXPENSE_REIMBURSE',
                'process_name' => 'Expense Reimbursement',
                'description' => 'Process for reimbursing employee expenses',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => '["1","2","3","4"]',
                'second_checker_roles' => '["1","2"]',
                'min_amount' => 0,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-09-05 12:00:00',
                'updated_at' => '2025-09-05 12:00:00',
                'requires_approver' => true,
                'approver_roles' => '["1"]',
            ],
            [
                'id' => 50,
                'process_code' => 'BUDGET_OVERRIDE',
                'process_name' => 'Budget Override',
                'description' => 'Process for approving expenses that exceed budget',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => '["1","2"]',
                'second_checker_roles' => '["1"]',
                'min_amount' => 0,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-09-05 12:00:00',
                'updated_at' => '2025-09-05 12:00:00',
                'requires_approver' => true,
                'approver_roles' => '["1"]',
            ],
            [
                'id' => 35,
                'process_code' => 'PAY_VENDOR',
                'process_name' => 'Vendor Payment',
                'description' => 'Approval for vendor payments',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 36,
                'process_code' => 'PAY_SALARY',
                'process_name' => 'Salary Payment',
                'description' => 'Approval for salary payments',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 37,
                'process_code' => 'INV_PLACE',
                'process_name' => 'Place Investment',
                'description' => 'Approval for placing investments',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 10000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 38,
                'process_code' => 'INV_WITHDRAW',
                'process_name' => 'Withdraw Investment',
                'description' => 'Approval for investment withdrawals',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 10000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 39,
                'process_code' => 'PROC_REQ',
                'process_name' => 'Procurement Request',
                'description' => 'Approval for procurement requests',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 40,
                'process_code' => 'PROC_PO',
                'process_name' => 'Purchase Order',
                'description' => 'Approval for purchase orders',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 41,
                'process_code' => 'BUDGET_CREATE',
                'process_name' => 'Create Budget',
                'description' => 'Approval for creating budgets',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 42,
                'process_code' => 'BUDGET_ADJUST',
                'process_name' => 'Adjust Budget',
                'description' => 'Approval for budget adjustments',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 43,
                'process_code' => 'BUDGET_EDIT',
                'process_name' => 'Edit Budget',
                'description' => 'Approval for editing existing budgets',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 44,
                'process_code' => 'BUDGET_DELETE',
                'process_name' => 'Delete Budget',
                'description' => 'Approval for deleting budgets',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 45,
                'process_code' => 'INS_POLICY',
                'process_name' => 'Insurance Policy',
                'description' => 'Approval for insurance policies',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 46,
                'process_code' => 'INS_CLAIM',
                'process_name' => 'Insurance Claim',
                'description' => 'Approval for insurance claims',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 45,
                'process_code' => 'TELLER_ASSIGN',
                'process_name' => 'Assign Teller',
                'description' => 'Approval for teller assignments',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 46,
                'process_code' => 'TELLER_CASH',
                'process_name' => 'Teller Cash Management',
                'description' => 'Approval for teller cash operations',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 5000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 47,
                'process_code' => 'RECON_DAILY',
                'process_name' => 'Daily Reconciliation',
                'description' => 'Approval for daily reconciliations',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 48,
                'process_code' => 'RECON_MONTHLY',
                'process_name' => 'Monthly Reconciliation',
                'description' => 'Approval for monthly reconciliations',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 49,
                'process_code' => 'HR_HIRE',
                'process_name' => 'Staff Hiring',
                'description' => 'Approval for new staff hiring',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 50,
                'process_code' => 'HR_TERMINATE',
                'process_name' => 'Staff Termination',
                'description' => 'Approval for staff termination',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 51,
                'process_code' => 'HR_SALARY',
                'process_name' => 'Salary Change',
                'description' => 'Approval for salary changes',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 52,
                'process_code' => 'SELF_PWD',
                'process_name' => 'Password Change',
                'description' => 'Approval for password changes',
                'requires_first_checker' => false,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 53,
                'process_code' => 'SELF_PROFILE',
                'process_name' => 'Profile Update',
                'description' => 'Approval for profile updates',
                'requires_first_checker' => false,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 54,
                'process_code' => 'REPORT_GEN',
                'process_name' => 'Generate Report',
                'description' => 'Approval for report generation',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 55,
                'process_code' => 'REPORT_EXPORT',
                'process_name' => 'Export Report',
                'description' => 'Approval for report exports',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 56,
                'process_code' => 'INST_SETTINGS',
                'process_name' => 'Institution Settings',
                'description' => 'Approval for institution settings changes',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 57,
                'process_code' => 'INST_PARAMS',
                'process_name' => 'System Parameters',
                'description' => 'Approval for system parameter changes',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 58,
                'process_code' => 'USER_CREATE',
                'process_name' => 'Create User',
                'description' => 'Approval for creating new users',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 59,
                'process_code' => 'USER_EDIT',
                'process_name' => 'Edit User',
                'description' => 'Approval for modifying user details',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 60,
                'process_code' => 'USER_DEACTIVATE',
                'process_name' => 'Deactivate User',
                'description' => 'Approval for deactivating users',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 61,
                'process_code' => 'LOAN_EXTEND',
                'process_name' => 'Extend Loan',
                'description' => 'Approval for loan extensions',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 62,
                'process_code' => 'LOAN_RESCHEDULE',
                'process_name' => 'Reschedule Loan',
                'description' => 'Approval for loan rescheduling',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 1000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 63,
                'process_code' => 'MGT_APPROVE',
                'process_name' => 'Management Approval',
                'description' => 'Approval for management-level decisions',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => 10000000.00,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 65,
                'process_code' => 'GROUP_CREATE',
                'process_name' => 'Create Group',
                'description' => 'Approval for creating new groups',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 66,
                'process_code' => 'GROUP_EDIT',
                'process_name' => 'Edit Group',
                'description' => 'Approval for modifying group details',
                'requires_first_checker' => true,
                'requires_second_checker' => false,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 67,
                'process_code' => 'GROUP_DISBAND',
                'process_name' => 'Disband Group',
                'description' => 'Approval for disbanding groups',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => null,
                'second_checker_roles' => null,
                'min_amount' => null,
                'max_amount' => null,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-17 16:25:51',
                'requires_approver' => true,
                'approver_roles' => null,
            ],
            [
                'id' => 64,
                'process_code' => 'MEMBER_REG',
                'process_name' => 'Member Registration',
                'description' => 'Approval for creating new members',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => '["1"]',
                'second_checker_roles' => '["1"]',
                'min_amount' => 0.00,
                'max_amount' => 100.00,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-18 03:35:18',
                'requires_approver' => true,
                'approver_roles' => '["1"]',
            ],
            [
                'id' => 19,
                'process_code' => 'LOAN_DISB',
                'process_name' => 'Loan Disbursement',
                'description' => 'Approval for loan disbursements',
                'requires_first_checker' => true,
                'requires_second_checker' => true,
                'first_checker_roles' => '["1"]',
                'second_checker_roles' => '["1"]',
                'min_amount' => 1000000.00,
                'max_amount' => 50000000.00,
                'is_active' => true,
                'created_at' => '2025-07-17 16:25:51',
                'updated_at' => '2025-07-18 07:08:12',
                'requires_approver' => true,
                'approver_roles' => '["1"]',
            ],
        ];

        foreach ($data as $row) {
            DB::table('process_code_configs')->insert($row);
    }
}
}