<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoleMenuActionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('role_menu_actions')->truncate();

        // Insert existing data
        $data = [
            [
                'id' => 1,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 1,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 2,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 2,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 3,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 3,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 4,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 4,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 5,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 5,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 6,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 6,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 7,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 7,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 8,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 8,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 9,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 9,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 10,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 10,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 11,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 11,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 12,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 12,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 13,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 13,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 14,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 14,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 15,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 15,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 16,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 16,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 17,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 17,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 18,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 18,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 19,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 19,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 20,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 20,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 21,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 21,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 22,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 22,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 23,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 23,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 24,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 24,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 25,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 25,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 26,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 26,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 27,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 27,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 28,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 28,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage","configure","audit"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 32,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 1,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 33,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 2,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 34,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 3,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 35,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 4,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 36,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 5,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 37,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 6,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 38,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 7,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 39,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 8,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 40,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 9,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 41,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 10,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 42,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 11,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 43,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 12,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 44,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 13,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 45,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 14,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 46,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 15,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 47,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 16,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 48,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 17,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 49,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 18,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 50,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 19,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 51,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 20,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 52,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 21,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 53,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 22,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 54,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 23,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 55,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 24,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 56,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 25,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 57,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 26,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 58,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 27,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 59,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 28,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 60,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 29,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 61,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 30,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 62,
                'role_id' => 2,
                'sub_role' => 'Institution Administrator',
                'menu_id' => 31,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 29,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 29,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 30,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 30,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
            [
                'id' => 31,
                'role_id' => 1,
                'sub_role' => 'System Administrator',
                'menu_id' => 31,
                'allowed_actions' => json_encode(['value' => '["view","create","edit","delete","approve","reject","manage"]']),
                'created_at' => '2025-07-17 16:25:46',
                'updated_at' => '2025-07-17 16:25:46',
            ],
        ];

        foreach ($data as $row) {
            DB::table('role_menu_actions')->insert($row);
    }
}
}