<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SaccosLoanProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $loanProducts = [
            [
                'sub_product_id' => 'NBC001',
                'product_id' => 'LOAN',
                'sub_product_name' => 'NBCSaccos butua',
                'prefix' => 'NBC',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 10000.00,
                'principle_max_value' => 150000.00,
                'min_term' => 1,
                'max_term' => 1,
                'interest_value' => '2.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.0,
                'maintenance_fees' => 'no',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'ONJA002',
                'product_id' => 'LOAN',
                'sub_product_name' => 'ONJA',
                'prefix' => 'ONJA',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 50000.00,
                'principle_max_value' => 1000000.00,
                'min_term' => 3,
                'max_term' => 3,
                'interest_value' => '5.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.0,
                'maintenance_fees' => 'no',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'EMG003',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA DHARURA',
                'prefix' => 'EMG',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 100000.00,
                'principle_max_value' => 4000000.00,
                'min_term' => 12,
                'max_term' => 12,
                'interest_value' => '2.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'DEV004',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA MAENDELEO MDOGO',
                'prefix' => 'DEV',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 200000.00,
                'principle_max_value' => 6000000.00,
                'min_term' => 18,
                'max_term' => 18,
                'interest_value' => '1.5',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'BIG005',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA MAENDELEO MKUBWA',
                'prefix' => 'BIG',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 1000000.00,
                'principle_max_value' => 40000000.00,
                'min_term' => 36,
                'max_term' => 36,
                'interest_value' => '1.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'HOM006',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA BIDHAA ZA NYUMBANI',
                'prefix' => 'HOM',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 100000.00,
                'principle_max_value' => 4000000.00,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => '2.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'PEN007',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA WASTAAFU',
                'prefix' => 'PEN',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 100000.00,
                'principle_max_value' => 4000000.00,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => '12.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'PEME008',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA WASTAAFU(DHARURA)',
                'prefix' => 'PEME',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 100000.00,
                'principle_max_value' => 4000000.00,
                'min_term' => 12,
                'max_term' => 12,
                'interest_value' => '1.8',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'CHP009',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA CHAPCHAP',
                'prefix' => 'CHP',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 50000.00,
                'principle_max_value' => 2000000.00,
                'min_term' => 3,
                'max_term' => 3,
                'interest_value' => '4.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.0,
                'maintenance_fees' => 'no',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'BUS010',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA BIASHARA',
                'prefix' => 'BUS',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 500000.00,
                'principle_max_value' => 20000000.00,
                'min_term' => 24,
                'max_term' => 24,
                'interest_value' => '2.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.3,
                'maintenance_fees' => 'yes',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'sub_product_id' => 'HOL011',
                'product_id' => 'LOAN',
                'sub_product_name' => 'MKOPO WA SIKUKUUU',
                'prefix' => 'HOL',
                'sub_product_status' => 'ACTIVE',
                'currency' => 'TZS',
                'principle_min_value' => 50000.00,
                'principle_max_value' => 1000000.00,
                'min_term' => 1,
                'max_term' => 1,
                'interest_value' => '5.0',
                'interest_tenure' => 'monthly',
                'interest_method' => 'reducing',
                'amortization_method' => 'equal_installments',
                'days_in_a_year' => 365,
                'days_in_a_month' => 30,
                'repayment_strategy' => 'monthly',
                'maintenance_fees_value' => 0.0,
                'maintenance_fees' => 'no',
                'ledger_fees' => 'no',
                'ledger_fees_value' => 0.0,
                'requires_approval' => 'yes',
                'allow_statement_generation' => 'yes',
                'send_notifications' => 'yes',
                'require_image_member' => 'no',
                'require_image_id' => 'no',
                'require_mobile_number' => 'yes',
                'institution_id' => '1',
                'repayment_frequency' => 'monthly',
                'penalty_value' => '5.0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Check if products already exist to avoid duplicates
        foreach ($loanProducts as $product) {
            $exists = DB::table('loan_sub_products')
                ->where('sub_product_id', $product['sub_product_id'])
                ->exists();
            
            if (!$exists) {
                DB::table('loan_sub_products')->insert($product);
                $this->command->info("✓ Inserted: {$product['sub_product_name']} (ID: {$product['sub_product_id']})");
            } else {
                $this->command->warn("⚠ Skipped: {$product['sub_product_name']} (ID: {$product['sub_product_id']}) - Already exists");
            }
        }

        $this->command->info("\n🎉 SACCOS Loan Products Seeder completed successfully!");
        $this->command->info("📊 Total products processed: " . count($loanProducts));
        
        // Display summary
        $totalProducts = DB::table('loan_sub_products')->count();
        $this->command->info("📈 Total loan products in database: {$totalProducts}");
    }
}
