<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('services')->truncate();

        // Insert existing data
        $data = [
            [
                'id' => 2,
                'name' => 'Loan Application Fee',
                'code' => 'LON',
                'description' => 'Application fee for SACCO loans',
                'is_mandatory' => false,
                'lower_limit' => 50000.00,
                'upper_limit' => 50000000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 3,
                'name' => 'Loan Repayment',
                'code' => 'REP',
                'description' => 'Repayment of SACCO loans',
                'is_mandatory' => true,
                'lower_limit' => 1000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 4,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 4,
                'name' => 'Savings Deposit',
                'code' => 'SAV',
                'description' => 'Deposit to savings account',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 10000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 6,
                'name' => 'Annual Subscription',
                'code' => 'SUB',
                'description' => 'Annual membership subscription fee',
                'is_mandatory' => true,
                'lower_limit' => 10000.00,
                'upper_limit' => 100000.00,
                'isRecurring' => true,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 7,
                'name' => 'Insurance Premium',
                'code' => 'INS',
                'description' => 'Member insurance premium payment',
                'is_mandatory' => false,
                'lower_limit' => 5000.00,
                'upper_limit' => 500000.00,
                'isRecurring' => true,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 8,
                'name' => 'Emergency Loan Repayment',
                'code' => 'EMG',
                'description' => 'Emergency loan repayment by members',
                'is_mandatory' => false,
                'lower_limit' => 10000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 9,
                'name' => 'Penalty Fee',
                'code' => 'PEN',
                'description' => 'Penalty fee for late payments or violations',
                'is_mandatory' => true,
                'lower_limit' => 1000.00,
                'upper_limit' => 100000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 10,
                'name' => 'Building Fund Contribution',
                'code' => 'BLD',
                'description' => 'Contribution towards SACCO building or infrastructure projects',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 5000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 11,
                'name' => 'Education Fund',
                'code' => 'EDU',
                'description' => 'Contribution to the SACCO education support fund',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 2000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-17 16:25:49',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 5,
                'name' => 'Registration Fee',
                'code' => 'REG',
                'description' => 'New member registration fee',
                'is_mandatory' => true,
                'lower_limit' => 50000.00,
                'upper_limit' => 500000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101400042004210',
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-18 03:49:12',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 1,
                'name' => 'Share Purchase',
                'code' => 'SHC',
                'description' => 'Purchase of SACCO shares by members',
                'is_mandatory' => true,
                'lower_limit' => 100000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101300030003003',
                'created_at' => '2025-07-17 16:25:49',
                'updated_at' => '2025-07-18 03:51:47',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
            [
                'id' => 12,
                'name' => 'Member Deposits',
                'code' => 'DIP',
                'description' => 'Member Deposits',
                'is_mandatory' => true,
                'lower_limit' => 10.00,
                'upper_limit' => 10000000.00,
                'isRecurring' => false,
                'paymentMode' => 5,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101200021002120',
                'created_at' => '2025-07-18 04:04:34',
                'updated_at' => '2025-07-18 04:04:34',
                'payment_mode' => 2,
                'is_recurring' => false,
            ],
        ];

        foreach ($data as $row) {
            DB::table('services')->insert($row);
    }
}
}