<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Combined seeder that includes all services from ServiceSeeder, ServicesSeeder, and ServicesTableSeeder
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('services')->truncate();

        // Comprehensive services data combining all three seeders
        $services = [
            // Core SACCO Services
            [
                // 'id' => 1,
                'name' => 'Share Purchase',
                'code' => 'SHC',
                'description' => 'Purchase of SACCO shares by members',
                'is_mandatory' => true,
                'lower_limit' => 100000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101300030003003',
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 2,
                'name' => 'Loan Application Fee',
                'code' => 'LON',
                'description' => 'Application fee for SACCO loans',
                'is_mandatory' => false,
                'lower_limit' => 50000.00,
                'upper_limit' => 50000000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 3,
                'name' => 'Loan Repayment',
                'code' => 'REP',
                'description' => 'Repayment of SACCO loans',
                'is_mandatory' => true,
                'lower_limit' => 1000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 4,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 4,
                'name' => 'Savings Deposit',
                'code' => 'SAV',
                'description' => 'Deposit to savings account',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 10000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 5,
                'name' => 'Registration Fee',
                'code' => 'REG',
                'description' => 'New member registration fee',
                'is_mandatory' => true,
                'lower_limit' => 50000.00,
                'upper_limit' => 500000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101400042004210',
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 6,
                'name' => 'Annual Subscription',
                'code' => 'SUB',
                'description' => 'Annual membership subscription fee',
                'is_mandatory' => true,
                'lower_limit' => 10000.00,
                'upper_limit' => 100000.00,
                'isRecurring' => true,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 7,
                'name' => 'Insurance Premium',
                'code' => 'INS',
                'description' => 'Member insurance premium payment',
                'is_mandatory' => false,
                'lower_limit' => 5000.00,
                'upper_limit' => 500000.00,
                'isRecurring' => true,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 8,
                'name' => 'Emergency Loan Repayment',
                'code' => 'EMG',
                'description' => 'Emergency loan repayment by members',
                'is_mandatory' => false,
                'lower_limit' => 10000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => true,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 9,
                'name' => 'Penalty Fee',
                'code' => 'PEN',
                'description' => 'Penalty fee for late payments or violations',
                'is_mandatory' => true,
                'lower_limit' => 1000.00,
                'upper_limit' => 100000.00,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 10,
                'name' => 'Building Fund Contribution',
                'code' => 'BLD',
                'description' => 'Contribution towards SACCO building or infrastructure projects',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 5000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 11,
                'name' => 'Education Fund',
                'code' => 'EDU',
                'description' => 'Contribution to the SACCO education support fund',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 2000000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 12,
                'name' => 'Member Deposits',
                'code' => 'DIP',
                'description' => 'Member Deposits',
                'is_mandatory' => true,
                'lower_limit' => 10.00,
                'upper_limit' => 10000000.00,
                'isRecurring' => false,
                'paymentMode' => 5,
                'debit_account' => '0101100010001010',
                'credit_account' => '0101200021002120',
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 13,
                'name' => 'Welfare Fund',
                'code' => 'WEL',
                'description' => 'Contribution to member welfare fund for emergencies',
                'is_mandatory' => false,
                'lower_limit' => 5000.00,
                'upper_limit' => 500000.00,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Additional Services from ServicesTableSeeder
            [
                // 'id' => 14,
                'name' => 'Monthly Membership Fee',
                'code' => 'MMF',
                'description' => 'Monthly membership contribution',
                'is_mandatory' => true,
                'lower_limit' => 10000.00,
                'upper_limit' => 50000.00,
                'isRecurring' => true,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 15,
                'name' => 'Emergency Loan',
                'code' => 'EML',
                'description' => 'Short-term emergency loan facility',
                'is_mandatory' => false,
                'lower_limit' => 100000.00,
                'upper_limit' => 1000000.00,
                'isRecurring' => false,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 1,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 16,
                'name' => 'Development Loan',
                'code' => 'DVL',
                'description' => 'Long-term development loan',
                'is_mandatory' => false,
                'lower_limit' => 500000.00,
                'upper_limit' => 5000000.00,
                'isRecurring' => false,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 1,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 17,
                'name' => 'Education Loan',
                'code' => 'EDL',
                'description' => 'Loan for educational purposes',
                'is_mandatory' => false,
                'lower_limit' => 200000.00,
                'upper_limit' => 2000000.00,
                'isRecurring' => false,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 1,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 18,
                'name' => 'Business Loan',
                'code' => 'BSL',
                'description' => 'Loan for business development',
                'is_mandatory' => false,
                'lower_limit' => 300000.00,
                'upper_limit' => 3000000.00,
                'isRecurring' => false,
                'paymentMode' => 1,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 1,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 19,
                'name' => 'Voluntary Savings',
                'code' => 'VSA',
                'description' => 'Voluntary savings contribution',
                'is_mandatory' => false,
                'lower_limit' => 5000.00,
                'upper_limit' => null,
                'isRecurring' => true,
                'paymentMode' => 5,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 5,
                'is_recurring' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 20,
                'name' => 'Fixed Deposit',
                'code' => 'FXD',
                'description' => 'Fixed deposit savings account',
                'is_mandatory' => false,
                'lower_limit' => 100000.00,
                'upper_limit' => null,
                'isRecurring' => false,
                'paymentMode' => 3,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 3,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 21,
                'name' => 'Late Payment Fee',
                'code' => 'LPF',
                'description' => 'Penalty for late payments',
                'is_mandatory' => false,
                'lower_limit' => 5000.00,
                'upper_limit' => 50000.00,
                'isRecurring' => false,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 22,
                'name' => 'Loan Processing Fee',
                'code' => 'LNF',
                'description' => 'Fee for processing loan applications',
                'is_mandatory' => true,
                'lower_limit' => 10000.00,
                'upper_limit' => 100000.00,
                'isRecurring' => false,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 23,
                'name' => 'Annual General Meeting Fee',
                'code' => 'AGM',
                'description' => 'Fee for annual general meeting attendance',
                'is_mandatory' => true,
                'lower_limit' => 5000.00,
                'upper_limit' => 20000.00,
                'isRecurring' => false,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                //  'id' => 24,
                'name' => 'Document Processing Fee',
                'code' => 'DPF',
                'description' => 'Fee for processing member documents',
                'is_mandatory' => false,
                'lower_limit' => 2000.00,
                'upper_limit' => 10000.00,
                'isRecurring' => false,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                // 'id' => 25,
                'name' => 'Withdrawal Fee',
                'code' => 'WDF',
                'description' => 'Fee for withdrawing savings',
                'is_mandatory' => false,
                'lower_limit' => 1000.00,
                'upper_limit' => 5000.00,
                'isRecurring' => false,
                'paymentMode' => 2,
                'debit_account' => null,
                'credit_account' => null,
                'payment_mode' => 2,
                'is_recurring' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert all services
        foreach ($services as $service) {
            DB::table('services')->insert($service);
        }
    }
}