<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubMenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('sub_menus')->truncate();

        // Insert existing data
        $data = [
            [
                'id' => 1,
                'system_id' => 1,
                'menu_id' => 1,
                'sub_menu_name' => 'View Branches',
                'user_action' => 'View Branches',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'system_id' => 1,
                'menu_id' => 1,
                'sub_menu_name' => 'Create Branch',
                'user_action' => 'Create Branch',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'system_id' => 1,
                'menu_id' => 1,
                'sub_menu_name' => 'Edit Branch',
                'user_action' => 'Edit Branch',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'system_id' => 1,
                'menu_id' => 1,
                'sub_menu_name' => 'Delete Branch',
                'user_action' => 'Delete Branch',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'system_id' => 1,
                'menu_id' => 2,
                'sub_menu_name' => 'View Members',
                'user_action' => 'View Members',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'system_id' => 1,
                'menu_id' => 2,
                'sub_menu_name' => 'Create Member',
                'user_action' => 'Create Member',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'system_id' => 1,
                'menu_id' => 2,
                'sub_menu_name' => 'Edit Member',
                'user_action' => 'Edit Member',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'system_id' => 1,
                'menu_id' => 2,
                'sub_menu_name' => 'Delete Member',
                'user_action' => 'Delete Member',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'system_id' => 1,
                'menu_id' => 3,
                'sub_menu_name' => 'View Shares',
                'user_action' => 'View Shares',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'system_id' => 1,
                'menu_id' => 3,
                'sub_menu_name' => 'Create Share',
                'user_action' => 'Create Share',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'system_id' => 1,
                'menu_id' => 3,
                'sub_menu_name' => 'Edit Share',
                'user_action' => 'Edit Share',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'system_id' => 1,
                'menu_id' => 3,
                'sub_menu_name' => 'Delete Share',
                'user_action' => 'Delete Share',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'system_id' => 1,
                'menu_id' => 4,
                'sub_menu_name' => 'View Savings',
                'user_action' => 'View Savings',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'system_id' => 1,
                'menu_id' => 4,
                'sub_menu_name' => 'Create Saving Account',
                'user_action' => 'Create Saving Account',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'system_id' => 1,
                'menu_id' => 4,
                'sub_menu_name' => 'Edit Saving Account',
                'user_action' => 'Edit Saving Account',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'system_id' => 1,
                'menu_id' => 4,
                'sub_menu_name' => 'Delete Saving Account',
                'user_action' => 'Delete Saving Account',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'system_id' => 1,
                'menu_id' => 5,
                'sub_menu_name' => 'View Deposits',
                'user_action' => 'View Deposits',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'system_id' => 1,
                'menu_id' => 5,
                'sub_menu_name' => 'Create Deposit',
                'user_action' => 'Create Deposit',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'system_id' => 1,
                'menu_id' => 5,
                'sub_menu_name' => 'Edit Deposit',
                'user_action' => 'Edit Deposit',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'system_id' => 1,
                'menu_id' => 5,
                'sub_menu_name' => 'Delete Deposit',
                'user_action' => 'Delete Deposit',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'View Loans',
                'user_action' => 'View Loans',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Create Loan',
                'user_action' => 'Create Loan',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Edit Loan',
                'user_action' => 'Edit Loan',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Delete Loan',
                'user_action' => 'Delete Loan',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'system_id' => 1,
                'menu_id' => 7,
                'sub_menu_name' => 'View Products',
                'user_action' => 'View Products',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'system_id' => 1,
                'menu_id' => 7,
                'sub_menu_name' => 'Create Product',
                'user_action' => 'Create Product',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'system_id' => 1,
                'menu_id' => 7,
                'sub_menu_name' => 'Edit Product',
                'user_action' => 'Edit Product',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'system_id' => 1,
                'menu_id' => 7,
                'sub_menu_name' => 'Delete Product',
                'user_action' => 'Delete Product',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'system_id' => 1,
                'menu_id' => 8,
                'sub_menu_name' => 'View Accounting Records',
                'user_action' => 'View Accounting Records',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'system_id' => 1,
                'menu_id' => 8,
                'sub_menu_name' => 'Create Accounting Entry',
                'user_action' => 'Create Accounting Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'system_id' => 1,
                'menu_id' => 8,
                'sub_menu_name' => 'Edit Accounting Entry',
                'user_action' => 'Edit Accounting Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'system_id' => 1,
                'menu_id' => 8,
                'sub_menu_name' => 'Delete Accounting Entry',
                'user_action' => 'Delete Accounting Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'system_id' => 1,
                'menu_id' => 9,
                'sub_menu_name' => 'View Expenses',
                'user_action' => 'View Expenses',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'system_id' => 1,
                'menu_id' => 9,
                'sub_menu_name' => 'Create Expense',
                'user_action' => 'Create Expense',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'system_id' => 1,
                'menu_id' => 9,
                'sub_menu_name' => 'Edit Expense',
                'user_action' => 'Edit Expense',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'system_id' => 1,
                'menu_id' => 9,
                'sub_menu_name' => 'Delete Expense',
                'user_action' => 'Delete Expense',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'system_id' => 1,
                'menu_id' => 10,
                'sub_menu_name' => 'View Payments',
                'user_action' => 'View Payments',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'system_id' => 1,
                'menu_id' => 10,
                'sub_menu_name' => 'Create Payment',
                'user_action' => 'Create Payment',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'system_id' => 1,
                'menu_id' => 10,
                'sub_menu_name' => 'Edit Payment',
                'user_action' => 'Edit Payment',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'system_id' => 1,
                'menu_id' => 10,
                'sub_menu_name' => 'Delete Payment',
                'user_action' => 'Delete Payment',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'system_id' => 1,
                'menu_id' => 11,
                'sub_menu_name' => 'View Investments',
                'user_action' => 'View Investments',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'system_id' => 1,
                'menu_id' => 11,
                'sub_menu_name' => 'Create Investment',
                'user_action' => 'Create Investment',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'system_id' => 1,
                'menu_id' => 11,
                'sub_menu_name' => 'Edit Investment',
                'user_action' => 'Edit Investment',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'system_id' => 1,
                'menu_id' => 11,
                'sub_menu_name' => 'Delete Investment',
                'user_action' => 'Delete Investment',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'system_id' => 1,
                'menu_id' => 12,
                'sub_menu_name' => 'View Procurement',
                'user_action' => 'View Procurement',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 46,
                'system_id' => 1,
                'menu_id' => 12,
                'sub_menu_name' => 'Create Procurement Entry',
                'user_action' => 'Create Procurement Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 47,
                'system_id' => 1,
                'menu_id' => 12,
                'sub_menu_name' => 'Edit Procurement Entry',
                'user_action' => 'Edit Procurement Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'system_id' => 1,
                'menu_id' => 12,
                'sub_menu_name' => 'Delete Procurement Entry',
                'user_action' => 'Delete Procurement Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 49,
                'system_id' => 1,
                'menu_id' => 13,
                'sub_menu_name' => 'View Budgets',
                'user_action' => 'View Budgets',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'system_id' => 1,
                'menu_id' => 13,
                'sub_menu_name' => 'Create Budget',
                'user_action' => 'Create Budget',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'system_id' => 1,
                'menu_id' => 13,
                'sub_menu_name' => 'Edit Budget',
                'user_action' => 'Edit Budget',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'system_id' => 1,
                'menu_id' => 13,
                'sub_menu_name' => 'Delete Budget',
                'user_action' => 'Delete Budget',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 53,
                'system_id' => 1,
                'menu_id' => 14,
                'sub_menu_name' => 'View Insurance Policies',
                'user_action' => 'View Insurance Policies',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'system_id' => 1,
                'menu_id' => 14,
                'sub_menu_name' => 'Create Insurance Policy',
                'user_action' => 'Create Insurance Policy',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'system_id' => 1,
                'menu_id' => 14,
                'sub_menu_name' => 'Edit Insurance Policy',
                'user_action' => 'Edit Insurance Policy',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 56,
                'system_id' => 1,
                'menu_id' => 14,
                'sub_menu_name' => 'Delete Insurance Policy',
                'user_action' => 'Delete Insurance Policy',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 57,
                'system_id' => 1,
                'menu_id' => 15,
                'sub_menu_name' => 'View Teller Transactions',
                'user_action' => 'View Teller Transactions',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 58,
                'system_id' => 1,
                'menu_id' => 15,
                'sub_menu_name' => 'Create Teller Transaction',
                'user_action' => 'Create Teller Transaction',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 59,
                'system_id' => 1,
                'menu_id' => 15,
                'sub_menu_name' => 'Edit Teller Transaction',
                'user_action' => 'Edit Teller Transaction',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 60,
                'system_id' => 1,
                'menu_id' => 15,
                'sub_menu_name' => 'Delete Teller Transaction',
                'user_action' => 'Delete Teller Transaction',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 61,
                'system_id' => 1,
                'menu_id' => 16,
                'sub_menu_name' => 'View Reconciliation Records',
                'user_action' => 'View Reconciliation Records',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 62,
                'system_id' => 1,
                'menu_id' => 16,
                'sub_menu_name' => 'Create Reconciliation Entry',
                'user_action' => 'Create Reconciliation Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 63,
                'system_id' => 1,
                'menu_id' => 16,
                'sub_menu_name' => 'Edit Reconciliation Entry',
                'user_action' => 'Edit Reconciliation Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 64,
                'system_id' => 1,
                'menu_id' => 16,
                'sub_menu_name' => 'Delete Reconciliation Entry',
                'user_action' => 'Delete Reconciliation Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 65,
                'system_id' => 1,
                'menu_id' => 17,
                'sub_menu_name' => 'View HR Records',
                'user_action' => 'View HR Records',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 66,
                'system_id' => 1,
                'menu_id' => 17,
                'sub_menu_name' => 'Create HR Entry',
                'user_action' => 'Create HR Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 67,
                'system_id' => 1,
                'menu_id' => 17,
                'sub_menu_name' => 'Edit HR Entry',
                'user_action' => 'Edit HR Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 68,
                'system_id' => 1,
                'menu_id' => 17,
                'sub_menu_name' => 'Delete HR Entry',
                'user_action' => 'Delete HR Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 69,
                'system_id' => 1,
                'menu_id' => 18,
                'sub_menu_name' => 'View Self Service Options',
                'user_action' => 'View Self Service Options',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 70,
                'system_id' => 1,
                'menu_id' => 18,
                'sub_menu_name' => 'Create Self Service Entry',
                'user_action' => 'Create Self Service Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 71,
                'system_id' => 1,
                'menu_id' => 18,
                'sub_menu_name' => 'Edit Self Service Entry',
                'user_action' => 'Edit Self Service Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 72,
                'system_id' => 1,
                'menu_id' => 18,
                'sub_menu_name' => 'Delete Self Service Entry',
                'user_action' => 'Delete Self Service Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 73,
                'system_id' => 1,
                'menu_id' => 19,
                'sub_menu_name' => 'View Approvals',
                'user_action' => 'View Approvals',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 74,
                'system_id' => 1,
                'menu_id' => 19,
                'sub_menu_name' => 'Create Approval Entry',
                'user_action' => 'Create Approval Entry',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 75,
                'system_id' => 1,
                'menu_id' => 19,
                'sub_menu_name' => 'Edit Approval Entry',
                'user_action' => 'Edit Approval Entry',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 76,
                'system_id' => 1,
                'menu_id' => 19,
                'sub_menu_name' => 'Delete Approval Entry',
                'user_action' => 'Delete Approval Entry',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 77,
                'system_id' => 1,
                'menu_id' => 20,
                'sub_menu_name' => 'View Reports',
                'user_action' => 'View Reports',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 78,
                'system_id' => 1,
                'menu_id' => 20,
                'sub_menu_name' => 'Create Report',
                'user_action' => 'Create Report',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 79,
                'system_id' => 1,
                'menu_id' => 20,
                'sub_menu_name' => 'Edit Report',
                'user_action' => 'Edit Report',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 80,
                'system_id' => 1,
                'menu_id' => 20,
                'sub_menu_name' => 'Delete Report',
                'user_action' => 'Delete Report',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 81,
                'system_id' => 1,
                'menu_id' => 21,
                'sub_menu_name' => 'View Institution Settings',
                'user_action' => 'View Institution Settings',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 82,
                'system_id' => 1,
                'menu_id' => 21,
                'sub_menu_name' => 'Edit Institution Settings',
                'user_action' => 'Edit Institution Settings',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 83,
                'system_id' => 1,
                'menu_id' => 22,
                'sub_menu_name' => 'View Users',
                'user_action' => 'View Users',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 84,
                'system_id' => 1,
                'menu_id' => 22,
                'sub_menu_name' => 'Create User',
                'user_action' => 'Create User',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 85,
                'system_id' => 1,
                'menu_id' => 22,
                'sub_menu_name' => 'Edit User',
                'user_action' => 'Edit User',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 86,
                'system_id' => 1,
                'menu_id' => 22,
                'sub_menu_name' => 'Delete User',
                'user_action' => 'Delete User',
                'status' => 'pending',
                'position' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 87,
                'system_id' => 1,
                'menu_id' => 23,
                'sub_menu_name' => 'Active Loans',
                'user_action' => 'Active Loan',
                'status' => 'pending',
                'position' => 24,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 88,
                'system_id' => 1,
                'menu_id' => 24,
                'sub_menu_name' => 'Management Approval',
                'user_action' => 'Management Approval',
                'status' => 'pending',
                'position' => 24,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 89,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Send Loan For Approval',
                'user_action' => 'Send Loan For Approval',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 90,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Can Approve Loan',
                'user_action' => 'Can Approve Loan',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 91,
                'system_id' => 1,
                'menu_id' => 6,
                'sub_menu_name' => 'Can Disburse Loan',
                'user_action' => 'Can Disburse Loan',
                'status' => 'pending',
                'position' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 92,
                'system_id' => 1,
                'menu_id' => 25,
                'sub_menu_name' => 'View Groups',
                'user_action' => 'View Groups',
                'status' => 'pending',
                'position' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 93,
                'system_id' => 1,
                'menu_id' => 25,
                'sub_menu_name' => 'Create Group',
                'user_action' => 'Create Group',
                'status' => 'pending',
                'position' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        foreach ($data as $row) {
            DB::table('sub_menus')->insert($row);
    }
}
}