<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Active Loans by Officer Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #366092;
            padding-bottom: 20px;
        }
        
        .header h1 {
            color: #366092;
            font-size: 24px;
            margin: 0 0 10px 0;
            font-weight: bold;
        }
        
        .header h2 {
            color: #666;
            font-size: 16px;
            margin: 0 0 5px 0;
            font-weight: normal;
        }
        
        .header p {
            color: #999;
            font-size: 10px;
            margin: 0;
        }
        
        .section {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        
        .section-title {
            background-color: #366092;
            color: white;
            padding: 8px 12px;
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
        }
        
        .summary-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .summary-row {
            display: table-row;
        }
        
        .summary-cell {
            display: table-cell;
            padding: 8px 12px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
            font-weight: bold;
            width: 25%;
        }
        
        .summary-value {
            display: table-cell;
            padding: 8px 12px;
            border: 1px solid #ddd;
            background-color: white;
        }
        
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 10px;
        }
        
        .table th {
            background-color: #366092;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        
        .table td {
            padding: 6px;
            border: 1px solid #ddd;
            vertical-align: top;
        }
        
        .table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .table tr.overdue {
            background-color: #ffebee;
        }
        
        .currency {
            text-align: right;
        }
        
        .center {
            text-align: center;
        }
        
        .status-normal {
            color: #4caf50;
            font-weight: bold;
        }
        
        .status-overdue {
            color: #f44336;
            font-weight: bold;
        }
        
        .status-active {
            color: #2196f3;
            font-weight: bold;
        }
        
        .footer {
            position: fixed;
            bottom: 20px;
            left: 20px;
            right: 20px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .no-data {
            text-align: center;
            color: #666;
            font-style: italic;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ACTIVE LOANS BY OFFICER REPORT</h1>
        <h2>Microfinance Institution</h2>
        <p>Generated on {{ now()->format('F d, Y \a\t g:i A') }} | Generated by {{ auth()->user()->name ?? 'System' }}</p>
        @if($selectedOfficer && $officerName)
            <p>Filtered by Officer: {{ $officerName }}</p>
        @else
            <p>All Officers</p>
        @endif
    </div>

    <!-- Summary Statistics -->
    <div class="section">
        <div class="section-title">SUMMARY STATISTICS</div>
        <div class="summary-grid">
            <div class="summary-row">
                <div class="summary-cell">Total Active Loans</div>
                <div class="summary-value">{{ $summary['totalLoans'] }}</div>
                <div class="summary-cell">Total Loan Amount</div>
                <div class="summary-value currency">{{ number_format($summary['totalLoanAmount'], 2) }} TZS</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Overdue Loans</div>
                <div class="summary-value">{{ $summary['overdueLoans'] }}</div>
                <div class="summary-cell">Active Officers</div>
                <div class="summary-value">{{ $summary['activeOfficers'] }}</div>
            </div>
        </div>
    </div>

    <!-- Officer Performance Summary (if filtered) -->
    @if($selectedOfficer && $officerName)
    <div class="section">
        <div class="section-title">OFFICER PERFORMANCE SUMMARY</div>
        <div class="summary-grid">
            <div class="summary-row">
                <div class="summary-cell">Officer Name</div>
                <div class="summary-value">{{ $officerName }}</div>
                <div class="summary-cell">Total Loans</div>
                <div class="summary-value">{{ $summary['officerLoans'] }}</div>
            </div>
            <div class="summary-row">
                <div class="summary-cell">Total Amount</div>
                <div class="summary-value currency">{{ number_format($summary['officerLoanAmount'], 2) }} TZS</div>
                <div class="summary-cell">Overdue Loans</div>
                <div class="summary-value">{{ $summary['officerOverdueLoans'] }}</div>
            </div>
        </div>
    </div>
    @endif

    <!-- Detailed Loan Information -->
    <div class="section">
        <div class="section-title">DETAILED LOAN INFORMATION</div>
        
        @if(count($loans) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th style="width: 8%;">#</th>
                    <th style="width: 15%;">Loan ID</th>
                    <th style="width: 18%;">Member Name</th>
                    <th style="width: 15%;">Guarantor</th>
                    <th style="width: 12%;">Branch</th>
                    <th style="width: 10%;">Principle (TZS)</th>
                    <th style="width: 8%;">Interest (%)</th>
                    <th style="width: 8%;">Past Due Days</th>
                    <th style="width: 15%;">Loan Officer</th>
                    <th style="width: 10%;">Loan Status</th>
                    <th style="width: 10%;">Action Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($loans as $index => $loan)
                <tr class="{{ $loan->days_in_arrears > 0 ? 'overdue' : '' }}">
                    <td class="center">{{ $index + 1 }}</td>
                    <td>{{ $loan->loan_id ?? 'N/A' }}</td>
                    <td>{{ $loan->member_name ?? 'N/A' }}</td>
                    <td>{{ $loan->guarantor_name ?? 'N/A' }}</td>
                    <td>{{ $loan->branch_name ?? 'N/A' }}</td>
                    <td class="currency">{{ number_format($loan->principle, 2) }}</td>
                    <td class="center">{{ $loan->interest }}%</td>
                    <td class="center {{ $loan->days_in_arrears > 0 ? 'status-overdue' : 'status-normal' }}">
                        {{ $loan->days_in_arrears ?? 0 }}
                    </td>
                    <td>{{ $loan->officer_name ?? 'N/A' }}</td>
                    <td class="center">
                        @if($loan->loan_status === 'NORMAL')
                            <span class="status-normal">NORMAL</span>
                        @elseif($loan->loan_status === 'OVERDUE')
                            <span class="status-overdue">OVERDUE</span>
                        @else
                            {{ $loan->loan_status ?? 'N/A' }}
                        @endif
                    </td>
                    <td class="center">
                        @if($loan->status === 'ACTIVE')
                            <span class="status-active">ACTIVE</span>
                        @else
                            {{ $loan->status ?? 'N/A' }}
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        
        <!-- Summary at bottom of table -->
        <div style="margin-top: 15px; padding: 10px; background-color: #f5f5f5; border: 1px solid #ddd;">
            <strong>Total Loans: {{ count($loans) }}</strong> | 
            <strong>Total Amount: {{ number_format($loans->sum('principle'), 2) }} TZS</strong> |
            <strong>Overdue Loans: {{ $loans->where('days_in_arrears', '>', 0)->count() }}</strong>
        </div>
        
        @else
        <div class="no-data">
            No active loans found for the selected criteria.
        </div>
        @endif
    </div>

    <!-- Additional Loan Details (if space permits) -->
    @if(count($loans) > 0 && count($loans) <= 10)
    <div class="section">
        <div class="section-title">ADDITIONAL LOAN DETAILS</div>
        <table class="table">
            <thead>
                <tr>
                    <th style="width: 15%;">Loan ID</th>
                    <th style="width: 20%;">Business Name</th>
                    <th style="width: 15%;">Collateral Type</th>
                    <th style="width: 15%;">Collateral Value (TZS)</th>
                    <th style="width: 15%;">Disbursement Date</th>
                    <th style="width: 20%;">Business Category</th>
                </tr>
            </thead>
            <tbody>
                @foreach($loans as $loan)
                <tr>
                    <td>{{ $loan->loan_id ?? 'N/A' }}</td>
                    <td>{{ $loan->business_name ?? 'N/A' }}</td>
                    <td>{{ $loan->collateral_type ?? 'N/A' }}</td>
                    <td class="currency">{{ number_format($loan->collateral_value ?? 0, 2) }}</td>
                    <td class="center">
                        {{ $loan->disbursement_date ? \Carbon\Carbon::parse($loan->disbursement_date)->format('Y-m-d') : 'N/A' }}
                    </td>
                    <td>{{ $loan->business_category ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the Microfinance Management System</p>
        <p>For questions or clarifications, please contact the IT Department</p>
    </div>
</body>
</html>

