<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Loan Loss Reserve Custom Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            background-color: #f4f4f4;
            padding: 8px;
            font-weight: bold;
            font-size: 14px;
            border-left: 4px solid #3498db;
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #34495e;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .summary-box {
            background-color: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .metric {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
            padding: 5px 0;
            border-bottom: 1px dotted #bdc3c7;
        }
        .metric-label {
            font-weight: bold;
            color: #2c3e50;
        }
        .metric-value {
            color: #27ae60;
            font-weight: bold;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .alert {
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 4px;
        }
        .alert-warning {
            background-color: #fcf8e3;
            border: 1px solid #faebcc;
            color: #8a6d3b;
        }
        .alert-success {
            background-color: #dff0d8;
            border: 1px solid #d6e9c6;
            color: #3c763d;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LOAN LOSS RESERVE CUSTOM REPORT</h1>
        <p><strong>Report Period:</strong> {{ $data['period']['start'] }} to {{ $data['period']['end'] }}</p>
        <p><strong>Generated On:</strong> {{ $data['generated_at'] }}</p>
        <p><strong>Generated By:</strong> {{ $data['generated_by'] }}</p>
    </div>

    @if(isset($data['provisions']))
    <div class="section">
        <div class="section-title">PROVISIONS SUMMARY</div>
        <div class="summary-box">
            <div class="metric">
                <span class="metric-label">Total Provisions:</span>
                <span class="metric-value">{{ number_format($data['provisions']->total_provisions ?? 0, 2) }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Number of Provisions:</span>
                <span class="metric-value">{{ $data['provisions']->provision_count ?? 0 }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Average Provision Amount:</span>
                <span class="metric-value">{{ number_format($data['provisions']->avg_provision ?? 0, 2) }}</span>
            </div>
        </div>
    </div>
    @endif

    @if(isset($data['writeoffs']))
    <div class="section">
        <div class="section-title">WRITE-OFFS SUMMARY</div>
        <div class="summary-box">
            <div class="metric">
                <span class="metric-label">Total Written Off:</span>
                <span class="metric-value">{{ number_format($data['writeoffs']->total_written_off ?? 0, 2) }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Number of Write-offs:</span>
                <span class="metric-value">{{ $data['writeoffs']->writeoff_count ?? 0 }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Average Write-off Amount:</span>
                <span class="metric-value">{{ number_format($data['writeoffs']->avg_writeoff ?? 0, 2) }}</span>
            </div>
        </div>

        @if($data['writeoffs']->writeoff_count > 0)
        <div class="alert alert-warning">
            <strong>Note:</strong> {{ $data['writeoffs']->writeoff_count }} loans were written off during this period, representing a total loss of {{ number_format($data['writeoffs']->total_written_off ?? 0, 2) }}.
        </div>
        @endif
    </div>
    @endif

    @if(isset($data['recoveries']))
    <div class="section">
        <div class="section-title">RECOVERIES SUMMARY</div>
        <div class="summary-box">
            <div class="metric">
                <span class="metric-label">Total Recovered:</span>
                <span class="metric-value">{{ number_format($data['recoveries']->total_recovered ?? 0, 2) }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Number of Recoveries:</span>
                <span class="metric-value">{{ $data['recoveries']->recovery_count ?? 0 }}</span>
            </div>
            <div class="metric">
                <span class="metric-label">Average Recovery Amount:</span>
                <span class="metric-value">{{ number_format($data['recoveries']->avg_recovery ?? 0, 2) }}</span>
            </div>
        </div>

        @if($data['recoveries']->recovery_count > 0)
        <div class="alert alert-success">
            <strong>Success:</strong> {{ $data['recoveries']->recovery_count }} recoveries were made during this period, recovering {{ number_format($data['recoveries']->total_recovered ?? 0, 2) }}.
        </div>
        @endif
    </div>
    @endif

    @if(isset($data['analytics']))
    <div class="section">
        <div class="section-title">PORTFOLIO ANALYTICS</div>
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NPL Ratio</td>
                    <td>{{ $data['analytics']['npl_ratio'] ?? 0 }}%</td>
                    <td>
                        @if(($data['analytics']['npl_ratio'] ?? 0) <= 5)
                            <span style="color: green;">✓ Within Limit</span>
                        @else
                            <span style="color: red;">✗ Above Threshold</span>
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>Coverage Ratio</td>
                    <td>{{ $data['analytics']['current_coverage_ratio'] ?? 0 }}%</td>
                    <td>
                        @if(($data['analytics']['current_coverage_ratio'] ?? 0) >= 100)
                            <span style="color: green;">✓ Adequate</span>
                        @else
                            <span style="color: orange;">⚠ Below Target</span>
                        @endif
                    </td>
                </tr>
                <tr>
                    <td>Recovery Rate</td>
                    <td>{{ $data['analytics']['average_recovery_rate'] ?? 0 }}%</td>
                    <td>
                        @if(($data['analytics']['average_recovery_rate'] ?? 0) >= 30)
                            <span style="color: green;">✓ Good</span>
                        @else
                            <span style="color: orange;">⚠ Needs Improvement</span>
                        @endif
                    </td>
                </tr>
            </tbody>
        </table>

        @if(isset($data['analytics']['portfolio_risk_distribution']))
        <div class="section-title" style="margin-top: 20px;">Risk Distribution</div>
        <table>
            <thead>
                <tr>
                    <th>Risk Category</th>
                    <th>Loan Count</th>
                    <th>Outstanding Amount</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['analytics']['portfolio_risk_distribution'] as $risk)
                <tr>
                    <td>{{ $risk->risk_category ?? 'Unknown' }}</td>
                    <td>{{ $risk->loan_count ?? 0 }}</td>
                    <td>{{ number_format($risk->outstanding_amount ?? 0, 2) }}</td>
                    <td>{{ number_format(($risk->percentage ?? 0), 1) }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>
    @endif

    <div class="footer">
        <p>This is a system-generated report. For any queries, please contact the Finance Department.</p>
        <p>© {{ date('Y') }} SACCOS Core System - Loan Loss Reserve Management</p>
    </div>
</body>
</html>